#!/bin/sh

#$ -N lbl_transfer
#$ -q IVR,CCOM,COE,UI,INFORMATICS
#$ -S /bin/bash
#$ -pe smp 56
#$ -l mf=2G
#$ -cwd
#$ -j y
#$ -l cpu_arch=broadwell
#$ -m be
#$ -M nathaniel-mullin@uiowa.edu


module load readline
module load bzip2
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/Shared/IVR/apvoigt/programs/R-4.1.0/lib64/R/lib:/opt/apps/libiconv/1.15/lib
module load libpng/1.6.28
module load icu/58.2
module load hdf5/1.8.18_gcc-5.4.0

echo ${1} # RNA data
echo ${2} # (integrated) ATAC data
echo ${3} # full file path including .RData extension where label-transfered object should be saved

/Shared/IVR/apvoigt/programs/R-4.1.0/bin/Rscript /Shared/IVR/apvoigt/experiments/sc-ATAC-seq/MELAS/2021_06_21_seurat_label_transfer.R \
--args ${1} ${2} ${3}



/Shared/IVR/apvoigt/experiments/sc-rna-seq/MELAS/data/2021_08_09_retina_rna_classified.RData /Shared/IVR/nkmullin/experiments/sc-atac-seq/melas_jci_insight_revision/lsi_10312022/integrated_final.RData /Shared/IVR/nkmullin/experiments/sc-atac-seq/melas_jci_insight_revision/lsi_10312022/integrated_final_with_trans_labels.RData

