#!/bin/sh

#$ -N sc_dge
#$ -q IVR,CCOM,COE,UI,INFORMATICS
#$ -S /bin/bash
#$ -pe smp 7
#$ -l mf=2G
#$ -cwd
#$ -j y
#$ -l cpu_arch=broadwell
#$ -e std_error

## ARG1: csv file of all arguments
## ARG2: SGE TASK ID

module load readline
module load bzip2
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/Shared/IVR/apvoigt/programs/R-4.1.0/lib64/R/lib:/opt/apps/libiconv/1.15/lib
module load libpng/1.6.28
module load icu/58.2
module load hdf5/1.8.18_gcc-5.4.0

/Shared/IVR/apvoigt/programs/R-4.1.0/bin/Rscript /Shared/IVR/nkmullin/experiments/sc-rna-seq/melas_jci_insight_revision/differential_expression/seurat_array_dge.R \
--args ${1} ${SGE_TASK_ID}