---
title: "melas_wnn_analysis"
author: "Nate Mullin"
date: "1/11/2023"
output: html_document
---

```{r}
library(Signac)
library(Seurat)
library("Signac")
library(tidyverse)
library(ggpubr)
library(EnsDb.Hsapiens.v86)
library(BSgenome.Hsapiens.UCSC.hg38)
library(ggrepel)
library(RColorBrewer)
library(scCustomize)
```

```{r}
load("~/LSS/IVR/nkmullin/experiments/multiome/melas_jci_insight_revision/seurat_downstream/wnn_analysis/for_github/multimodal_object_stringent_rpecho_draft_annotation.RData")
```

#plot

```{r}

# plot outcomes of WNN analysis
  # load rpe/chor colors!
p1 <- DimPlot(multimodal_object, reduction = "integrated_umap", group.by = "wsnn_res.0.5", label = TRUE, label.size = 2.5, repel = TRUE) + ggtitle("RNA")
p2 <- DimPlot(multimodal_object, reduction = "lsi_umap", group.by = "wsnn_res.0.5", label = TRUE, label.size = 2.5, repel = TRUE) + ggtitle("ATAC")
p3 <- DimPlot(multimodal_object, reduction = "wnn.umap", group.by = "wsnn_res.0.5", label = TRUE, label.size = 2.5, repel = TRUE) + ggtitle("WNN")



pdf(file = "melas_wnn_triple_umap_rpecho.pdf",  
    width = 15,
    height = 5)
p1 + p2 + p3 & NoLegend() & theme(plot.title = element_text(hjust = 0.5))
dev.off()
```


```{r}
donor_wnn_dim <- DimPlot(multimodal_object,shuffle = T, pt.size = 0.1, group.by = "dataset", reduction = "wnn.umap") + ggtitle("RPE/Choroid Multimodal Seq")

pdf(file = "donor_wnn_dimplot_rpecho_02023034.pdf",   # The directory you want to save the file in
    width = 8, # The width of the plot in inches
    height = 5) # The height of the plot in inches
donor_wnn_dim 
dev.off()
```



```{r}

pdf("rpecho_pred_score.pdf", width=5, height=5)
FeaturePlot(multimodal_object, features =  "prediction.score.max", reduction = "wnn.umap", pt.size = 0.01, order = F)
dev.off()

pdf("dimplot_rpecho_draft_annotation.pdf", width=5, height=5)
DimPlot(multimodal_object, reduction = "wnn.umap", shuffle = T, label = T, group.by = "draft_celltype", ncol = 1, cols = c(brewer.pal(n = 10, name = "Set1"), 
brewer.pal(n = 10, name = "Dark2"))) + NoLegend()
dev.off()
```

